name: Deploy to S3

on:
  push:
    branches:
      - master  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'  # Change to your preferred version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
        SOURCE_DIR : build
