name: CI/CD for React App

on:
  push:
    branches:
      - master  # Use 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'  # Your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
        env:
          REACT_APP_TEST: ${{ secrets.REACT_APP_TEST }}
          REACT_APP_TEST2: ${{ secrets.REACT_APP_TEST2 }}
          REACT_APP_GOOGLE_CLIENT_ID : ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_S3_BUCKET_NAME_FOR_MEDIA : ${{ secrets.REACT_APP_S3_BUCKET_NAME_FOR_MEDIA }}
          REACT_APP_AWS_REGION : ${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_AWS_ACCESS_KEY_ID : ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          REACT_APP_AWS_SECRET_ACCESS_KEY : ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}


      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.REACT_APP_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './build'